# Stage 1 - Builder
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install --only=production
COPY . .

# Stage 2 - Production (Distroless)
FROM gcr.io/distroless/nodejs20
WORKDIR /app
COPY --from=builder /app /app

EXPOSE 3000
CMD ["index.js"]
